services:
  postgres:
    image: postgres:15-alpine
    container_name: vtasker-postgres
    environment:
      POSTGRES_USER: vtasker
      POSTGRES_PASSWORD: vtasker_dev
      POSTGRES_DB: vtasker
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vtasker"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: vtasker-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
    name: vtasker-postgres-data
  redis-data:
    name: vtasker-redis-data 