# Air configuration for hot reload when running from /backend directory
root = ".."  # Important! Points to project root
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/main.go"  # Adjusted path
bin = "./tmp/main"
include_ext = ["go", "html", "tmpl", "tpl"]
exclude_dir = ["frontend", "tmp", "vendor", "testdata", "docs", "e2e", "node_modules"]
include_dir = ["backend"]
exclude_file = []
log = "air.log"
delay = 1000 # ms
stop_on_error = true
send_interrupt = true  # Better for Gin applications
kill_delay = "1s"

[log]
time = false
show_prefix = true
debug = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true 