apiVersion: v1
kind: Namespace
metadata:
  name: vtasker-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vtasker-manager
  namespace: vtasker-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vtasker-manager
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors", "prometheusrules"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vtasker-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vtasker-manager
subjects:
- kind: ServiceAccount
  name: vtasker-manager
  namespace: vtasker-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vtasker-config
  namespace: vtasker-system
data:
  config.yaml: |
    log:
      level: info
      format: json
    metrics:
      prometheus:
        url: http://prometheus-operated:9090
    logging:
      loki:
        url: http://loki:3100
    auth:
      jwt:
        secret: ${JWT_SECRET}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vtasker-manager
  namespace: vtasker-system
  labels:
    app: vtasker
    component: manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vtasker
      component: manager
  template:
    metadata:
      labels:
        app: vtasker
        component: manager
    spec:
      serviceAccountName: vtasker-manager
      containers:
      - name: manager
        image: vtasker/manager:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: CONFIG_FILE
          value: /etc/vtasker/config.yaml
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: vtasker-secrets
              key: jwt-secret
        volumeMounts:
        - name: config
          mountPath: /etc/vtasker
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: vtasker-config
---
apiVersion: v1
kind: Service
metadata:
  name: vtasker-manager
  namespace: vtasker-system
  labels:
    app: vtasker
    component: manager
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  - port: 9090
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app: vtasker
    component: manager
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vtasker-manager
  namespace: vtasker-system
  labels:
    app: vtasker
    component: manager
spec:
  selector:
    matchLabels:
      app: vtasker
      component: manager
  endpoints:
  - port: metrics
    interval: 15s 