# vTasker Configuration File

project:
  name: vTasker
  version: 0.1.0
  description: AI-powered task management system
  repository: https://github.com/yourusername/vTasker

tasks:
  directory: .vtask/tasks
  naming:
    pattern: task-{number}
    counter_digits: 3
    subtask_separator: "-"
  templates:
    directory: .vtask/templates
    default: task.template.md
  statuses:
    - backlog
    - in-progress
    - review
    - done

boards:
  directory: .vtask/boards
  default_settings:
    wip_limits:
      in_progress: 3
      review: 2
    auto_archive:
      enabled: true
      after_days: 30

ai:
  default_settings:
    automation_level: moderate
    task_creation: ai-assisted
    task_assignment: ai-suggested
    analysis_frequency: on-change 